[[main]]
  name = "Ecosystem"
  url = "https://ecosystem.akash.network"
  weight = 40
  [main.params]
    external = true


[[main]]
  name = "Community"
  url = "/community/"
  weight = 10


[[main]]
  name = "Docs"
  url = "https://docs.akash.network"
  weight = 20
  [main.params]
    external = true

[[main]]
  name = "Discussions"
  url = "https://github.com/orgs/akash-network/discussions"
  weight = 20
  [main.params]
    external = true

[[main]]
  name = "Token"
  url = "/token/"
  weight = 20

[[token]]
  name = "Bar"
  url = "https://ipfs.io/ipfs/QmdV52bF7j4utynJ6L11RgG93FuJiUmBH1i7pRD6NjUt6B"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20


[[main]]
  name = "Discussions"
  url = "https://github.com/orgs/akash-network/discussions"
  weight = 20
    [main.params]
    external = true

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/akash-network"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/akashnet_"
  weight = 20

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.`116089\"><path d=\"M8.9988 9.99918L8.9988 9.99918V9.99992C8.9988 10.4515 8.86991 10.856 8.66253 11.1461C8.45519 11.4361 8.1724 11.6085 7.86176 11.6085C7.55717 11.6085 7.27428 11.4363 7.06529 11.1459C6.8564 10.8557 6.72473 10.4512 6.72473 9.99992C6.72473 9.54832 6.85362 9.14383 7.061 8.85375C7.26834 8.56374 7.55113 8.3913 7.86176 8.3913C8.17256 8.3913 8.45829 8.56391 8.66703 8.8539C8.87575 9.14388 9.00452 9.54808 8.9988 9.99918ZM11.0012 9.99992C11.0012 9.54832 11.1301 9.14383 11.3375 8.85375C11.5448 8.56374 11.8276 8.3913 12.1383 8.3913C12.4429 8.3913 12.7258 8.56356 12.9347 8.8539C13.1436 9.14411 13.2753 9.54861 13.2753 9.99992C13.2753 10.4515 13.1464 10.856 12.939 11.1461C12.7317 11.4361 12.4489 11.6085 12.1383 11.6085C11.8337 11.6085 11.5508 11.4363 11.3418 11.1459C11.1329 10.8557 11.0012 10.4512 11.0012 9.99992Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"0.116089\"/><path d=\"M3.08287 6.33153C3.08293 6.33143 3.08298 6.33134 3.08304 6.33124C5.33116 4.8989 7.44165 4.18095 10.0041 4.1684C12.5323 4.15602 14.704 4.91179 16.9163 6.33013C16.9166 6.33059 16.9169 6.33106 16.9171 6.33153C16.979 6.43745 17.0695 6.59728 17.1791 6.80523C17.3985 7.22151 17.6935 7.82839 17.989 8.57978C18.5558 10.0214 19.1132 11.9664 19.1616 14.1032C19.1468 14.1193 19.1309 14.1362 19.1139 14.1539C18.9566 14.3176 18.7049 14.5481 18.3462 14.7854C17.7058 15.2089 16.7045 15.6671 15.25 15.7892L14.4845 14.4058L14.1379 13.7793L13.4659 14.0263C11.3461 14.8053 8.67454 14.7858 6.53658 14.0101L5.86333 13.7658L5.51938 14.394L4.74741 15.804C3.29431 15.6815 2.29432 15.2235 1.65492 14.7992C1.29646 14.5614 1.04548 14.3301 0.889114 14.1657C0.870853 14.1465 0.853895 14.1282 0.838221 14.111C0.885405 11.9711 1.44347 10.0231 2.01101 8.57978C2.30648 7.82839 2.60146 7.22151 2.82091 6.80523C2.93053 6.59728 3.02101 6.43745 3.08287 6.33153ZM19.3679 14.9477C19.2609 14.7906 19.1718 14.5086 19.165 14.4021H19.9998C19.9989 14.4028 19.995 14.408 19.9879 14.4172C19.9424 14.477 19.7666 14.7076 19.4372 14.9996C19.4119 14.9828 19.3886 14.9654 19.3679 14.9477ZM20 14.4021H20.835H20ZM3.17316 6.18118C3.17317 6.18116 3.17317 6.18116 3.17316 6.18117L3.17316 6.18118Z\" stroke=\"currentColor\" stroke-width=\"1.67\" stroke-linejoin=\"round\"/></svg>"
  url = "https://discord.akash.network"
  weight = 30

[[footer]]
  name = "Brand Guidelines"
  url = "https://brandpad.io/akash-network/"
  weight = 10

[[footer]]
  name = "Shop"
  url = "https://shop.akash.network/"
  weight = 10

[[footer]]
  name = "Logos"
  url = "https://github.com/akash-network/brand-assets"
  weight = 10

[[footer]]
  name = "Privacy"
  url = "/privacy"
  weight = 20
